version: '3.7'

services:

  mongodb:
    image: mongo:4.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: userdb
    ports:
      - 10000:27017
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: rabbitmq
        fluentd-address: localhost:10004

  mysql:
    image: mysql:8.0.15
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: purchasedb
    ports:
      - 10001:3306
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: rabbitmq
        fluentd-address: localhost:10004

  rabbitmq:
    image: rabbitmq:3.7.11-management
    environment:
      RABBITMQ_DEFAULT_VHOST: messages
    ports:
      - 10002:5672
      - 10003:15672
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        tag: rabbitmq
        fluentd-address: localhost:10004

  fluentd:
    build: ./docker/fluentd
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    ports:
      - 10004:24224
      - 10004:24224/udp
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:6.6.0
    ports:
      - 10005:9200

  kibana:
    image: kibana:6.6.0
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - 10006:5601
    depends_on:
      - elasticsearch