version: '3.7'

services:

  mongodb:
    image: mongo:4.0.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: userdb
    ports:
      - 10000:27017

  mysql:
    image: mysql:8.0.15
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: purchasedb
    ports:
      - 10001:3306

  rabbitmq:
    image: rabbitmq:3.7.11-management
    environment:
      RABBITMQ_DEFAULT_VHOST: messages
    ports:
      - 10002:5672
      - 10003:15672
