################################################################
# API and dashboard configuration
################################################################

[api]

################################################################
# Docker configuration backend
################################################################

[docker]
watch = true
exposedByDefault = false
